/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybank;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class bankAccount extends javax.swing.JFrame {

    public bankAccount() throws Exception {
       
        initComponents();
        setLocationRelativeTo(null);
        
        id.setText(Login.id.getText());
       // fname.setText(Register.Firstname.getText());
         try {
            ResultSet rs = DatabaseCon.getData("SELECT firstname FROM user WHERE idnumber ='"+id.getText()+"'");
            if(rs.next()){
                fname.setText(rs.getString("firstname"));// TODO add your handling code here:
            }
            else {
                
                
            
                System.out.println("Problem!!!");
            }
            
        } catch (Exception ex ) {
            Logger.getLogger(bankAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
          try {
            ResultSet is= DatabaseCon.getData("SELECT Accnumber FROM accounts WHERE idnumber ='"+id.getText()+"'");
            if (is.next()){
             
                accno.setText(is.getString("Accnumber"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        deposit = new javax.swing.JButton();
        withdraw = new javax.swing.JButton();
        bal = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p.setBackground(new java.awt.Color(248, 248, 255));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Welcome");

        fname.setEditable(false);
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("ID Number :");

        id.setEditable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Account Number:");

        accno.setEditable(false);
        accno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnoActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        Title.setText("MNB Bank");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        deposit.setText("Deposit");
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });

        withdraw.setText("Withdraw");
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });

        bal.setText("Balance");
        bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLayout = new javax.swing.GroupLayout(p);
        p.setLayout(pLayout);
        pLayout.setHorizontalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLayout.createSequentialGroup()
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(accno, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addGroup(pLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(id))))
                        .addGap(167, 167, 167)
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdraw)
                            .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        pLayout.setVerticalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLayout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLayout.createSequentialGroup()
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addComponent(deposit)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bal)))
                .addGap(26, 26, 26)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdraw))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
      
    }//GEN-LAST:event_fnameActionPerformed
   
    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed

    }//GEN-LAST:event_idActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        try {
            DatabaseCon.getCon().close();
        } catch (Exception ex) {
            Logger.getLogger(bankAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balActionPerformed
     Account acc=new Account();
                 JOptionPane.showMessageDialog(null, "Balance: " + acc.getBalance(), "Account", JOptionPane.PLAIN_MESSAGE);
                 
                 
          
        
                        // TODO add your handling code here:
    }//GEN-LAST:event_balActionPerformed

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
     try {
             
         try {
             Account acc = new Account();
           
             acc.deposit(0);
             
             System.out.println("Balance:"+acc.getBalance());
             
             DatabaseCon.setData("UPDATE accounts set Balance ='"+acc.getBalance()+"' where Idnumber= '"+Login.id.getText()+"'");
             
            JOptionPane.showMessageDialog(null, "Your balance is : " + acc.getBalance(), "Balance", JOptionPane.PLAIN_MESSAGE);
             
             
         } 
             catch (Exception ex) {
             Logger.getLogger(bankAccount.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        }
         catch(NullPointerException e){
         int CANCEL_OPTION = JOptionPane.CANCEL_OPTION;
         int CLOSED_OPTION = JOptionPane.CLOSED_OPTION;
            }


            /*Deposit d =new Deposit();
            d.setVisible(true);
            d.setResizable(true);
            dispose();

            /* String input = JOptionPane.showInputDialog(this,"Enter amount to deposit ","Deposit",JOptionPane.PLAIN_MESSAGE);
            double amount = 0;
            Account acc= new Account();
            try{

                amount = Double.parseDouble(input);
                DatabaseCon.setData("INSERT into account(Balance) VALUES ('"+input.getText()+"' )");

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Invalid deposit amount:"+input, "Invalid Deposit", JOptionPane.ERROR_MESSAGE);
            }
            if(amount < 0) {
                JOptionPane.showMessageDialog(null, "Invalid deposit Amount: " + input, "Invalid Deposit", JOptionPane.ERROR_MESSAGE);
                return;
            }
            */
       
    }//GEN-LAST:event_depositActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        try {
             
        try{
           

            try {
            Account acc = new Account();
            

            acc.withdraw(0);
             
            System.out.println("Balance:"+acc.getBalance());
                
                DatabaseCon.setData("UPDATE accounts set Balance ='"+acc.getBalance()+"' where Idnumber= '"+Login.id.getText()+"'");
                JOptionPane.showMessageDialog(null, "Your balance is : " + acc.getBalance(), "Balance", JOptionPane.PLAIN_MESSAGE);
              
            } catch (Exception ex) {
                Logger.getLogger(bankAccount.class.getName()).log(Level.SEVERE, null, ex);
            }

            /* Withdraw w =new Withdraw();
            w.setVisible(true);
            w.setResizable(true);
            dispose();*/

        } catch (Exception ex) {
            Logger.getLogger(bankAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
         catch(NullPointerException e){
         int CLOSED_OPTION = JOptionPane.CLOSED_OPTION;
            }
            

           

        /* Withdraw w =new Withdraw();
        w.setVisible(true);
        w.setResizable(true);
        dispose();*/

    }//GEN-LAST:event_withdrawActionPerformed

    private void accnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnoActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_accnoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    public static javax.swing.JTextField accno;
    private javax.swing.JButton bal;
    private javax.swing.JButton deposit;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fname;
    public static javax.swing.JTextField id;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel p;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables

  
}
